sudo: false
language: node_js
node_js:
  - 'stable'
script:
  - npm run build
  - npm test
env:
  global:
    # SAUCE_USER
    - secure: HQVsIlMzEXjE9TrZtBn/V9/g3uID2+F89ofI3PydhmlSFr5UiLgjGTBTs4JljpiwVQZNPvAAeew6BMGSmdbTgQHqtLwJzTYLP23lwmKGw40fjSzFPmHh9651IC7o9cFF1z738jsABUBaA3aeG5v8FVFIK0AWN/iGGKjN+7PKcYlONKn56ORPzFGVXsMlDVbefWhyxfBNUngAJKAH6ggmekodnB2Y9WBT09i68LRdEOkxIsegPiMFjnTxyaLa1PhR4adWlDQgcRvikhwoQXPZxCVZR1fAsLkauTWH+a3GoZPUmJxLwx4r6kFZwNch1nCxGzx+ol2GWulmRDyYKjE3hRTqRNH9Az4wyZpq+JJy5tYBME+g3LG1wrK1I/MImVLVkaNEhK8DIOD0AnYsehMW6Zh8hSaCIH0HL/BCH4ICdZLCZprKRuLsUogqQmqA7UJZkpxEH3JXD10M9a49AdRLy7Or+Pkpl+FAvW3omtL4SsVxPVhcZgF/G0esHrwrrtHwVr2l/iY0aKC1R07jZIfuMTujNeI3YKJrRPMLI5YIoJIGEnzVpExH3Ft+Ta/6VL41vNbliqNrrXc6G1evoJ1k72Q8NdXafnohPwE6DEcvCEyKsY3gO+d3ifgTV6D9FggJcR2+uFPxykMkO3XmtIevnEYtbbVKGT7Nb9vONoWkgLg=
    # SAUCE_KEY
    - secure: gYLqQn4KpMnc7T3KkZyyVzhJlP41vfCrvsIAjKJ0JByTJaLtYCLL8fEqYFJZOaOkPwc/uw3VGmLov9O0Gw1U6EfY8lnGyv+M+h2+tjzuBKSSqUkRsoUjHLoCXY/BJX6ZdnaoqfR3p0mkrVUXcPvCx6ER4omyhunmwdDV3KhHW93RN2N3DZ3nKbQiXLNAepD0WFe059yRhgG8JUjSHl/iJAPiyPRQwj0114a7J1YC4BOOvhuWGVo4lRM5fxXbsLQneztZFlK0pFtZ4kA7PItgbjknHyt9TGZZBLoJshBV21Z9YUPuUM0AxC9UgEPsLSbMUo65OrJac/ISERt5H1rYx2yNigM0QBdV06dUQ+II1tFff6H3xiflj4ZJsucYK5W6UQME9RiKzfTTSZhxbxW88dbmP/uWLdX2bA2n+a1F8TkxIL9F92SakJcMXHAe4QQdkbx6Q26wUd0r1oej54Sw3JRB1XqILRD5OpBWusw69v5puo/QWatzQnqDMw1HQgvAFFHb5ZahlD1D2kVyT23jD2IedQrxnxLnJPwbalNCHYK8iEjreGnVwMvXHeFjEhX2JbxVOckCpOUW28Xs/i8kfEAFdOc1kxKRhQwbC5Payc7MqsFL3p51JJ1lyMLQXide7cSjREZLVjeM7K68CRrg/72dTgNts1PltdQRQevlPkE=
    - PLATFORM='Windows 10'
    - BROWSER=Chrome
